version: '3.8'

services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db


  rabbitmq:
    image: rabbitmq:3.6.14-management
    healthcheck:
        interval: 30s
        timeout: 10s
        retries: 5
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"

  
  app:
    build: .
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - rabbitmq
      - db

volumes:
  mongo-data: